
namespace CheatBlackList
{
    class ModConfig
    {
        public string[] ModBlackListIds { get; set; } = {
            "ddde5195-8f85-4061-90cc-0d4fd5459358" ,
            "Pokeytax.AdjustablePriceHikes" ,
            "cantorsdust.AllCropsAllSeasons" ,
            "cantorsdust.AllProfessions" ,
            "439" ,
            "AaronTaggart.AutoAnimalDoors" ,
            "Jotser.AutoGrabberMod" ,
            "Permamiss.AutoEat" ,
            "WhiteMind.AF" ,
            "Pathoschild.Automate" ,
            "Omegasis.AutoSpeed" ,
            "Whisk.AutoWater" ,
            "DefenTheNation.BackpackResizer" ,
            "lrsk_sdvm_bsi.0117171308" ,
            "cat.betterhay" ,
            "hawkfalcon.BetterJunimos" ,
            "Speeder.BetterSprinklers" ,
            "f4iTh.BetterTransmutation" ,
            "lperkins2.BigSilo" ,
            "BunnyJumps.BJSNoClip" ,
            "BunnyJumps.BJSStopGrass" ,
            "BunnyJumps.BJSTimeSkipper" ,
            "Bregodon.BregsFish" ,
            "Omegasis.BuildEndurance" ,
            "Omegasis.BuildHealth" ,
            "CasksAnywhere" ,
            "Duder.ChefsCloset" ,
            "Pathoschild.ChestsAnywhere" ,
            "CJBok.CheatsMenu" ,
            "CJBok.ItemSpawner" ,
            "21da6619-dc03-4660-9794-8e5b498f5b97" ,
            "SMAPI.ConsoleCommands" ,
            "DIGUS.CropTransplantMod" ,
            "hawkfalcon.CustomQuestExpiration" ,
            "cat.customwarplocations" ,
            "KoihimeNakamura.CCR" ,
            "cat.customizabledeathpenalty" ,
            "Omegasis.DailyQuestAnywhere" ,
            "Pathoschild.DebugMode" ,
            "DynamicMachines" ,
            "MercuriusXeno.EquivalentExchange" ,
            "DIGUS.EverlastingBaitsAndUnbreakableTacklesMod" ,
            "Uwazouri.ExpandedFridge" ,
            "spacechase0.ExtendedReach" ,
            "DevinLematty.ExtremeFishingOverhaul" ,
            "misscoriel.EZLegendaryFish" ,
            "DeathGameDev.FastTravel" ,
            "kibbe.faster_horse" ,
            "KathrynHazuka.FasterRun" ,
            "shuaiz.FishingAdjustMod" ,
            "Drynwynn.FishingAutomaton" ,
            "Fokson.Foxyfficiency" ,
            "treyh0.GodMode" ,
            "bcmpinc.HarvestWithScythe", "965169fd-e1ed-47d0-9f12-b104535fb4bc" ,
            "icepuente.HorseWhistle" ,
            "LordAndreios.IdleTimer" ,
            "Demiacle.ImprovedQualityOfLife" ,
            "DevinLematty.InfiniteInventory" ,
            "renny.infinitejunimocartlives" ,
            "BitwiseJonMods.InstantBuildings" ,
            "cantorsdust.InstantGrowTrees" ,
            "Kabigon.kisekae" ,
            "hootless.JASprinklers", "hootless.LineSprinklers" ,
            "caraxian.LongerLastingLures" ,
            "UnlockedRecipes.pseudohub.de" ,
            "spacechase0.LuckSkill" ,
            "spacechase0.Magic" ,
            "MiningWithExplosives" ,
            "YonKuma.MoodGuard" ,
            "451" ,
            "rc.maps" ,
            "JadeTheavas.MoreMineLadders" ,
            "Omegasis.MoreRain" ,
            "OrneryWalrus.MoreSiloStorage" ,
            "shuaiz.MoveFasterMod" ,
            "ylsama.MoveThoughObject" ,
            "bcmpinc.MovementSpeed" ,
            "miome.MultiToolMod" ,
            "cat.nocrows" ,
            "Drynwynn.NoAddedFlyingMineMonsters" ,
            "Platonymous.NoSoilDecayRedux" ,
            "BitwiseJonMods.OneClickShedReloader" ,
            "SolomonsWorkshop.ParsnipsAbsolutelyEverywhere" ,
            "SB_PotC" ,
            "punyo.PassableObjects" ,
            "Vylus.PelicanPostalService" ,
            "DewMods.StardewValleyMods.PhoneVillagers" ,
            "f4iTh.PMT" ,
            "jwdred.PointAndPlant" ,
            "Mucchan.PrairieKingMadeEasy" ,
            "skuldomg.priceDrops" ,
            "BadNetCode.QuestDelay" ,
            "WuestMan.QuickStart" ,
            "KevinConnors.RealisticFishing" ,
            "cantorsdust.RecatchLegendaryFish" ,
            "Remmie.Rename" ,
            "JarvieK.RentedTools" ,
            "jwdred.Replanter" ,
            "Roc.Reseed" ,
            "cat.safelightning" ,
            "mmanlapat.ScytheHarvesting" ,
            "midoriarmstrong.seasonalitems" ,
            "spacechase0.SeedCatalogue" ,
            "GuiNoya.SelfServiceShop" ,
            "JarvieK.SelfService" ,
            "DewMods.StardewValleyMods.SkipFishingMinigame" ,
            "SkullCavernElevator" ,
            "littleraskol.SprintAndDashRedux" ,
            "SPDSprintAndDash" ,
            "mmanlapat.StartingMoney" ,
            "TehPers.FishingOverhaul" ,
            "hawkfalcon.TillableGround" ,
            "Omegasis.TimeFreeze" ,
            "DefenTheNation.TimeMultiplier" ,
            "cantorsdust.TimeSpeed" ,
            "crazywig.toolpowerselect" ,
            "Pathoschild.TractorMod",
            "TreeTransplant" ,
            "Shadowfoxss.UltimateGoldStardew" ,
            "RTGOAT.Longevity" ,
            "Shalankwa.WarpToFriends" ,
            "wHatsUp" ,
            "cat.wintergrass",
        };

        public string[] ModBlackListNames { get; set; } = {
            "A Tapper's Dream",
            "Adjustable Price Hikes",
            "All Crops All Seasons",
            "All Professions",
            "Almighty Farming Tool",
            "Auto Animal Doors",
            "Auto Grabber",
            "AutoEat",
            "AutoFish",
            "Automate",
            "AutoSpeed",
            "AutoWater",
            "Backpack Resizer",
            "Basic Sprinkler Improved",
            "Better Hay",
            "Better Junimos",
            "Better Sprinklers",
            "Better Transmutation",
            "Big Silos",
            "BJS No Clip",
            "BJS Stop Grass",
            "BJS Time Skipper",
            "Bregs Fish",
            "Build Endurance",
            "Build Health",
            "Casks Anywhere",
            "Chefs Closet",
            "Chests Anywhere",
            "CJB Cheats Menu",
            "CJB Item Spawner",
            "Configurable Machines",
            "Console Commands",
            "Crop Transplant",
            "Custom Quest Expiration",
            "Custom Warp Locations",
            "Customizable Cart Redux",
            "Customizable Death Penalty",
            "Daily Quest Anywhere",
            "Debug Mode",
            "Dynamic Machines",
            "Equivalent Exchange",
            "Everlasting Baits and Unbreakable Tackles",
            "Expanded Fridge",
            "Extended Reach",
            "Extreme Fishing Overhaul",
            "EZ Legendary Fish",
            "Fast Travel",
            "Faster Horse",
            "Faster Run",
            "Fishing Adjust",
            "Fishing Automaton",
            "Foxyfficiency",
            "God Mode",
            "Harvest With Scythe",
            "Horse Whistle",
            "Idle Timer",
            "Improved Quality of Life",
            "Infinite Inventory",
            "Infinite Junimo Cart Lives",
            "Instant Buildings",
            "Instant Grow Trees",
            "Kisekae",
            "Line Sprinklers",
            "Longer Lasting Lures",
            "Longevity",
            "Luck Skill",
            "Magic",
            "Mining With Explosives",
            "Mood Guard",
            "More Artifact Spots",
            "More Map Warps",
            "More Mine Ladders",
            "More Rain",
            "More Silo Storage",
            "Move Faster",
            "Move Though Object",
            "Movement Speed",
            "MultiTool",
            "No Crows",
            "No More Random Mine Flyers",
            "No Soil Decay Redux",
            "One Click Shed Reloader",
            "Parsnips Absolutely Everywhere",
            "Part of the Community",
            "Passable Objects",
            "Pelican Postal Service",
            "Phone Villagers",
            "Plantable Mushroom Trees",
            "Point And Plant",
            "Prairie King Made Easy",
            "Price Drops",
            "Quest Delay",
            "Quick Start",
            "Realistic Fishing",
            "Recatch Legendary Fish",
            "Rename",
            "Rented Tools",
            "Replanter",
            "Rocs Reseed",
            "Safe Lightning",
            "Scythe Harvesting",
            "Seasonal Items",
            "Seed Catalogue",
            "Self Service Shops",
            "Self Service",
            "Skip Fishing Minigame",
            "Skull Cavern Elevator",
            "Sprint and Dash Redux",
            "Sprint and Dash",
            "Starting Money",
            "Tehs Fishing Overhaul",
            "Tillable Ground",
            "Time Freeze",
            "Time Multiplier",
            "TimeSpeed",
            "Tool Power Select",
            "Tractor Mod",
            "Tree Transplant",
            "Ultimate Gold",
            "Unlocked Cooking Recipes",
            "Warp To Friends",
            "wHats Up",
            "Winter Grass",
        };
    }
}
